// Customizer const
export const TOGGLE_COLLAPSED_NAV = "TOGGLE_COLLAPSE_MENU";
export const WINDOW_WIDTH = "WINDOW-WIDTH";
export const SWITCH_LANGUAGE = "SWITCH-LANGUAGE";

//Contact Module const
export const FETCH_START = "FETCH_START";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const HIDE_MESSAGE = "HIDE_MESSAGE";

export const SET_LOADER = "SET_LOADER";
export const ON_SHOW_LOADER = "ON_SHOW_LOADER";
export const ON_HIDE_LOADER = "ON_HIDE_LOADER";
export const SET_PREVPATH = "SET_PREVPATH";

//Auth const
export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNIN_GOOGLE_USER = "SIGNIN_GOOGLE_USER";
export const SIGNIN_GOOGLE_USER_SUCCESS = "SIGNIN_GOOGLE_USER_SUCCESS";
export const SIGNIN_FACEBOOK_USER = "SIGNIN_FACEBOOK_USER";
export const SIGNIN_FACEBOOK_USER_SUCCESS = "SIGNIN_FACEBOOK_USER_SUCCESS";
export const SIGNIN_TWITTER_USER = "SIGNIN_TWITTER_USER";
export const SIGNIN_TWITTER_USER_SUCCESS = "SIGNIN_TWITTER_USER_SUCCESS";
export const SIGNIN_GITHUB_USER = "SIGNIN_GITHUB_USER";
export const SIGNIN_GITHUB_USER_SUCCESS = "signin_github_user_success";
export const SIGNIN_USER = "SIGNIN_USER";
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
export const SIGNOUT_USER = "SIGNOUT_USER";
export const SIGNOUT_USER_SUCCESS = "SIGNOUT_USER_SUCCESS";
export const INIT_URL = "INIT_URL";
export const USER_DATA = "USER_DATA";
export const USER_TOKEN_SET = "USER_TOKEN_SET";
export const UPDATE_LOAD_USER = "UPDATE_LOAD_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const SET_ONBOARD_SUCCESS = "SET_ONBOARD_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER = "UPDATE_USER";

//Account
export const REDIRECTED_DASHBOARD = "REDIRECTED_DASHBOARD";

// Scroll Positions and Views
export const SET_SCROLL_POSITION = "SET_SCROLL_POSITION";

export const SET_FEEDBACK_PAGE_SCROLL_POSITION =
  "SET_FEEDBACK_PAGE_SCROLL_POSITION";
export const SET_STAFF_PAGE_SCROLL_POSITION = "SET_STAFF_PAGE_SCROLL_POSITION";
export const SET_LOCATION_PAGE_SCROLL_POSITION =
  "SET_LOCATION_PAGE_SCROLL_POSITION";
export const SET_BRAND_PAGE_SCROLL_POSITION = "SET_BRAND_PAGE_SCROLL_POSITION";
export const SET_ACCOUNT_PAGE_SCROLL_POSITION =
  "SET_ACCOUNT_PAGE_SCROLL_POSITION";

export const SET_FEEDBACK_INDEX_SCROLL_POSITION =
  "SET_FEEDBACK_INDEX_SCROLL_POSITION";
export const SET_LOCATIONS_INDEX_SCROLL_POSITION =
  "SET_LOCATIONS_INDEX_SCROLL_POSITION";
export const SET_BRANDS_INDEX_SCROLL_POSITION =
  "SET_BRANDS_INDEX_SCROLL_POSITION";
export const SET_ACCOUNTS_INDEX_SCROLL_POSITION =
  "SET_ACCOUNTS_INDEX_SCROLL_POSITION";
export const SET_USERS_INDEX_SCROLL_POSITION =
  "SET_USERS_INDEX_SCROLL_POSITION";
export const SET_SUBSCRIPTIONS_INDEX_SCROLL_POSITION =
  "SET_SUBSCRIPTIONS_INDEX_SCROLL_POSITION";

export const SET_LOCATION_PAGE_FEEDBACK_TABLE =
  "SET_LOCATION_PAGE_FEEDBACK_TABLE";
export const SET_LOCATION_PAGE_STAFF_TABLE = "SET_LOCATION_PAGE_STAFF_TABLE";
export const RESET_LOCATION_PAGE_TABLES = "RESET_LOCATION_PAGE_TABLES";

export const SET_BRAND_PAGE_FEEDBACK_TABLE = "SET_BRAND_PAGE_FEEDBACK_TABLE";
export const SET_BRAND_PAGE_LOCATION_TABLE = "SET_BRAND_PAGE_LOCATION_TABLE";
export const SET_BRAND_PAGE_STAFF_TABLE = "SET_BRAND_PAGE_STAFF_TABLE";
export const RESET_BRAND_PAGE_TABLES = "RESET_BRAND_PAGE_TABLES";

export const SET_ACCOUNT_PAGE_FEEDBACK_TABLE =
  "SET_ACCOUNT_PAGE_FEEDBACK_TABLE";
export const SET_ACCOUNT_PAGE_LOCATIONS_TABLE =
  "SET_ACCOUNT_PAGE_LOCATIONS_TABLE";
export const SET_ACCOUNT_PAGE_BRANDS_TABLE = "SET_ACCOUNT_PAGE_BRANDS_TABLE";
export const SET_ACCOUNT_PAGE_USERS_TABLE = "SET_ACCOUNT_PAGE_USERS_TABLE";
export const RESET_ACCOUNT_PAGE_TABLES = "RESET_ACCOUNT_PAGE_TABLES";

export const SET_FEEDBACK_INDEX_TABLE = "SET_FEEDBACK_INDEX_TABLE";
export const SET_LOCATIONS_INDEX_TABLE = "SET_LOCATIONS_INDEX_TABLE";
export const SET_BRANDS_INDEX_TABLE = "SET_BRANDS_INDEX_TABLE";
export const SET_ACCOUNTS_INDEX_TABLE = "SET_ACCOUNTS_INDEX_TABLE";
export const SET_USERS_INDEX_TABLE = "SET_USERS_INDEX_TABLE";
export const SET_SUBSCRIPTIONS_INDEX_TABLE = "SET_SUBSCRIPTIONS_INDEX_TABLE";

export const SET_LOCATION_TAB = "SET_LOCATION_TAB";
export const SET_BRAND_TAB = "SET_BRAND_TAB";
export const SET_ACCOUNT_TAB = "SET_ACCOUNT_TAB";

export const SET_BREADCRUMB_CLICK = "SET_BREADCRUMB_CLICK";

export const SET_SUBSCRIPTION = "SET_SUBSCRIPTION";
export const UPDATE_SUBSCRIPTION = "UPDATE_SUBSCRIPTION";
export const UPDATE_SUBSCRIPTION_STEP = "UPDATE_SUBSCRIPTION_STEP";
export const CLEAR_SUBSCRIPTION = "CLEAR_SUBSCRIPTION";

export const UPDATE_SETUP = "UPDATE_SETUP";
export const CLEAR_SETUP = "CLEAR_SETUP";
